accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view() ,name='logout'),
    path('signup/',views.SignUp.as_view() ,name='signup'),
]

posts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# from .views import SearchView

app_name = 'posts'
urlpatterns = [
    path('',views.post_list, name = 'post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',views.post_detail,name='post_detail'),
    path('tag/<slug:tag_slug>/',views.post_list, name = 'post_list_by_tag'),
    path('search/',views.post_search , name = 'post_search'),
    path('projects/',views.project_list , name = 'projects_list'),
    path('about/',views.about_list , name = 'about'),
    path('contact/',views.contact, name = 'contact'),
    path('new/',views.new_post, name='new'),
    path('edit_post/<int:year>/<int:month>/<int:day>/<slug:post>',views.edit_post ,name = 'edit_post'),
    path('delete/<int:year>/<int:month>/<int:day>/<slug:post>',views.delete ,name = 'delete')
    # path('edit_post/<int:year>/<int:month>/<int:day>/<slug:post>', UpdatePost.as_view(),name = 'edit_post')
    # path('add_photo/',views.add_gallery, name = 'add_photo'),
    # path('gallery/',views.gallery_list,name = 'gallery'),
    # path('gallery/<int:year>/<int:month>/<int:day>/<slug:image>/',views.gallery_detail,name='gallery_detail'),
]

skn3/urls.py
from django.contrib import admin
from django.urls import path,include
from posts import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('',views.post_home , name ='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('posts/',include('posts.urls',namespace='posts'))
] + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
        urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
{% load blog_tags %}
{% load static %}
<html lang="en">

<head>
  <title>SKN Geodetów</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='shortcut icon' type='image/x-icon' href='/favicon.ico' />
  <link href="https://fonts.googleapis.com/css?family=B612+Mono|Cabin:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'skn/fonts/icomoon/style.css' %}">

  <link rel="stylesheet" href="{% static 'skn/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'skn/css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'skn/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'skn/css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'skn/css/owl.theme.default.min.css' %}">

  <link rel="stylesheet" href="{% static 'skn/css/jquery.fancybox.min.css' %}">

  <link rel="stylesheet" href="{% static 'skn/css/bootstrap-datepicker.css' %}">

  <link rel="stylesheet" href="{% static 'skn/fonts/flaticon/font/flaticon.css' %}">

  <link rel="stylesheet" href="{% static 'skn/css/aos.css' %}">
  <link href="{% static 'skn/css/jquery.mb.YTPlayer.min.css' %}" media="all" rel="stylesheet" type="text/css">

  <link rel="stylesheet" href="{% static 'skn/css/style.css' %}">



</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>



    <div class="header-top">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-12 col-lg-6 d-flex">
            <a href="{% url 'home' %}" class="site-logo">
                <img src="{% static 'skn/images/sknlogo.png' %}" alt="" width="18%">
            </a>

            <a href="#" class="ml-auto d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black"><span
                class="icon-menu h3"></span></a>

          </div>
          <div class="col-12 col-lg-6 ml-auto d-flex">
            <div class="ml-md-auto top-social d-none d-lg-inline-block">
              <a href="https://www.facebook.com/SKNGeodetow/" class="d-inline-block p-3"><span class="icon-facebook"></span></a>
                <a href="https://www.instagram.com/skn_geodetow_upwr/" class="d-inline-block p-3"><span class="icon-instagram"></span></a>
            </div>
            <form action="{% url 'posts:post_search' %}"  method="GET" class="search-form d-inline-block">
                <div class="d-flex">
                    <input type="text" value="{{request.GET.q}}" name="q" class="form-control" placeholder="Szukaj..."/>
                    <button type="submit" class="btn btn-secondary" ><span class="icon-search"></span></button>
                </div>
            </form>


          </div>
          <div class="col-6 d-block d-lg-none text-right">

          </div>
        </div>
      </div>




      <div class="site-navbar py-2 js-sticky-header site-navbar-target d-none pl-0 d-lg-block" role="banner">

      <div class="container">
        <div class="d-flex align-items-center">

          <div class="mr-auto">
            <nav class="site-navigation position-relative text-right" role="navigation">
              <ul class="site-menu main-menu js-clone-nav mr-auto d-none pl-0 d-lg-block">
                <li class="active">
                  <a href="{% url 'home' %}" class="nav-link text-left">Strona Główna</a>
                </li>
                <li>
                  <a href="{% url 'posts:about' %}" class="nav-link text-left">O nas</a>
                </li>
                <li>
                  <a href="{% url 'posts:post_list' %}" class="nav-link text-left">Aktualności</a>
                </li>
                <li>
                  <a href="{% url 'posts:projects_list' %}" class="nav-link text-left">Projekty naukowe</a>
                </li>
{#                <li>#}
{#                    <a href="{% url 'posts:gallery' %}" class="nav-link text-left">Galeria</a>#}
{#                </li>#}
                <li><a href="{% url 'posts:contact' %}" class="nav-link text-left">Kontakt</a></li>
{#                  {% if user.is_authenticated %}#}
                  {% if perms.posts.can_add_post %}
                <li>
                    <a href="{% url 'accounts:logout' %}" class="nav-link text-left">Wyloguj</a>
                </li>
                      <li>
                          <a href="{% url 'posts:new' %}">Stwórz post</a>
                      </li>
                  {% else %}
                      <li>
                          <a href="{% url 'accounts:login' %}" class="nav-link text-left">Zaloguj</a>
                      </li>
                      <li>
                          <a href="{% url 'accounts:signup' %}">Zarejestruj</a>
                      </li>
                  {% endif %}
              </ul>
            </nav>

          </div>

        </div>
      </div>

    </div>

    </div>



    <div class="site-section">
      <div class="container">
        <div class="row">
                <div class="col-lg-8 single-content">
                {% block content %}
                {% endblock %}
{#                <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>#}
{#                <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span></span>#}
                </div>
                <div class="col-lg-4 ml-auto">
                    <div class="section-title">
                        <h2>Ostatnie posty</h2>
                    </div>
                    {% show_latest_post 3 %}
                    <p><a href="{% url 'posts:post_list' %}" class="more">Zobacz wszystkie posty<span class="icon-keyboard_arrow_right"></span></a>
                </p>
                </div>
      </div>
    </div>
    <div class="footer">
      <div class="container">


        <div class="row">
          <div class="col-12">
            <div class="copyright">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> SKN Geodetów | Made for
                    <img src="{% static 'skn/images/sknlogo.png' %}"  width="2%" alt=""> by Michał Lasia <a
                        href="">@115485</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>
  </div>
  <!-- .site-wrap -->


  <!-- loader -->
  <div id="loader" class="show fullscreen">
      <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#ff5e15"/>
      </svg>
  </div>

  <script src="{% static 'skn/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'skn/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'skn/js/jquery-ui.js' %}"></script>
  <script src="{% static 'skn/js/popper.min.js'%}"></script>
  <script src="{% static 'skn/js/bootstrap.min.js'%}"></script>
  <script src="{% static 'skn/js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'skn/js/jquery.stellar.min.js'%}"></script>
  <script src="{% static 'skn/js/jquery.countdown.min.js'%}"></script>
  <script src="{% static 'skn/js/bootstrap-datepicker.min.js'%}"></script>
  <script src="{% static 'skn/js/jquery.easing.1.3.js'%}"></script>
  <script src="{% static 'skn/js/aos.js'%}"></script>
  <script src="{% static 'skn/js/jquery.fancybox.min.js'%}"></script>
  <script src="{% static 'skn/js/jquery.sticky.js'%}"></script>
  <script src="{% static 'skn/js/jquery.mb.YTPlayer.min.js'%}"></script>




  <script src="{% static 'skn/js/main.js' %}"></script>

</body>

</html>

templates/index.html
{% extends '../../skn3/templates/base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        <div></div>

    {% endif %}
    <div class="container">
        <div class="col-M"></div>
    <h1></h1>
    </div>

{% endblock %}