posts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# from .views import SearchView

app_name = 'posts'
urlpatterns = [
    path('',views.post_list, name = 'post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',views.post_detail,name='post_detail'),
    path('tag/<slug:tag_slug>/',views.post_list, name = 'post_list_by_tag'),
    path('search/',views.post_search , name = 'post_search'),
    path('projects/',views.project_list , name = 'projects_list'),
    path('about/',views.about_list , name = 'about'),
    path('contact/',views.contact, name = 'contact'),
    path('new/',views.new_post, name='new'),
    path('edit_post/<int:year>/<int:month>/<int:day>/<slug:post>',views.edit_post ,name = 'edit_post'),
    path('delete/<int:year>/<int:month>/<int:day>/<slug:post>',views.delete ,name = 'delete')
    # path('edit_post/<int:year>/<int:month>/<int:day>/<slug:post>', UpdatePost.as_view(),name = 'edit_post')
    # path('add_photo/',views.add_gallery, name = 'add_photo'),
    # path('gallery/',views.gallery_list,name = 'gallery'),
    # path('gallery/<int:year>/<int:month>/<int:day>/<slug:image>/',views.gallery_detail,name='gallery_detail'),
]

skn3/urls.py
from django.contrib import admin
from django.urls import path,include
from posts import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('',views.post_home , name ='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('posts/',include('posts.urls',namespace='posts'))
] + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
        urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

posts/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from posts.utils import unique_slug_generator
from django.db.models.signals import pre_save

# Create your models here.
class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager, self).get_queryset().filter(status='published')


class ProjectManager(models.Manager):
    def get_queryset(self):
        return super(ProjectManager, self).get_queryset().filter(status='projects')


class AboutManager(models.Manager):
    def get_queryset(self):
        return super(AboutManager, self).get_queryset().filter(status='about')


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'), ('projects', 'Projects'), ('about', 'About'))
    title = models.CharField(max_length=250, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    objects = models.Manager()
    published = PublishManager()
    projects = ProjectManager()
    about = AboutManager()
    created = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)
    slug = models.SlugField(unique_for_date='publish', max_length=250)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post_detail', args=[
            self.publish.year,
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug])

def slug_generator(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator,sender=Post)



# Gallery doesn't work actually


class Gallery(models.Model):
    title = models.CharField(max_length=256,null=True,blank=True,default='dupa')
    file = models.FileField(upload_to="files/%Y/%m/%d")
    publish = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(unique_for_date='publish', max_length=250)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:gallery_detail', args=[
            self.publish.year,
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug])

posts/forms.py
from django.db import models
from django import forms
from .models import Post,Gallery
from django import forms
from django.forms import ClearableFileInput
class ModelPost(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'author',
            'body',
            'tags',
            'status',
        ]

class Filles(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ['title','file']
        widgets = {
            'file': ClearableFileInput(attrs={'multiple': True}),
        }

posts/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models import Q
from .forms import  ModelPost
from django.contrib import messages
from django.views.generic.edit import UpdateView
from django.contrib.auth.decorators import login_required,permission_required


"""POST LIST ZWRACA GRUPĘ/LISTE POSTÓW"""


def post_list(request, tag_slug=None):
    object = Post.published.all()
    paginator = Paginator(object, 3)
    page = request.GET.get('page')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object = object.filter(tags__in=[tag])
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #     Jeśli zmienna page nie jest liczba całkowitą pobierana jest pierwsza strona wyników
        posts = paginator.page(1)
    except EmptyPage:
        #     Jeśli zmienna page ma wartość wieksza niz numer ostatniej strony wwtedy pobierana jest ostatnia strone
        posts = paginator.page(paginator.num_pages)
    return render(request, 'posts/post_list.html', {'page': page,
                                                    'posts': posts,
                                                    'tag': tag, })
    # 'search_tearm':search_term})


"""POST DETAIL ZWRACA JEDNEGO POSTA"""


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day, )
    post_tags_id = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_id).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'posts/post_detail.html', {'post': post,
                                                      'similar_posts': similar_posts})


""" UŻYJ POST_DETAIL DLA STRONA GŁÓWNA W CELU WYŚWIETLENIA POSTA NAJNOWSZEGO DODAJ SOBIE FILTR"""


def post_home(request):
    posts = Post.published.all()
    return render(request, 'posts/actual.html', {'posts': posts})


@permission_required('posts.can_change_post')
def edit_post(request, year, month, day, post):
    template = 'posts/edit.html'
    post = get_object_or_404(Post, slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day, )
    if request.method == 'POST':
        form = ModelPost(request.POST or None, instance=post)
        # try:
        if form.is_valid():
            form.save()
            messages.success(request, "Post updated")
            return HttpResponseRedirect(post.get_absolute_url())
        # except Exception as e:
        #     messages.warning(request, 'Post nie został dodany przez błąd: {}'.format(e))

    else:
        form = ModelPost(instance=post)

    context = {'form': form,
               'post': post}
    return render(request, template, context)


@permission_required('posts.can_delete_post')
def delete(request, year, month, day, post):
    template = 'posts/delete.html'
    post = get_object_or_404(Post, slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day, )
    if request.method == 'POST':
        post.delete()
        # return HttpResponseRedirect('home')
        return render(request,'posts/actual.html')
    context = {'post': post}
    return render(request, template, context)

"""Wyszukiwanie postów"""


def post_search(request):
    if request.method == 'GET':
        query = request.GET.get('q')

        submitbutton = request.GET.get('submit')

        if query is not None:
            lookups = Q(title__icontains=query) | Q(content__icontains=query)

            results = Post.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(
                similarity__gt=0.025).order_by('-similarity')
            # results = Post.objects.annotate(rank=TrigramSimilarity('title',query)).filter(rank__gte=0.025).order_by('rank')

            context = {'results': results,
                       'submitbutton': submitbutton}

            return render(request, 'posts/search.html', context)

        else:
            return render(request, 'posts/search.html')

    else:
        return render(request, 'posts/search.html')


def project_list(request, tag_slug=None):
    object = Post.projects.all()
    paginator = Paginator(object, 3)
    page = request.GET.get('page')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object = object.filter(tags__in=[tag])
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #     Jeśli zmienna page nie jest liczba całkowitą pobierana jest pierwsza strona wyników
        posts = paginator.page(1)
    except EmptyPage:
        #     Jeśli zmienna page ma wartość wieksza niz numer ostatniej strony wwtedy pobierana jest ostatnia strone
        posts = paginator.page(paginator.num_pages)
    return render(request, 'posts/projects_lists.html', {'page': page,
                                                         'posts': posts,
                                                         'tag': tag, })


def about_list(request, tag_slug=None):
    posts = Post.about.order_by('-publish')[:1]
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    return render(request, 'posts/about.html', {'posts': posts,
                                                'tag': tag, })


def contact(request):
    return render(request, 'posts/contact.html')


@permission_required('posts.can_add_post')
def new_post(request):
    submitted = False
    if request.method == 'POST':
        form = ModelPost(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            form.save()
            # assert False
            return HttpResponseRedirect('/posts/new?submitted=True')
    else:
        form = ModelPost()
        if 'submitted' in request.GET:
            submitted = True

    return render(request,
                  'posts/new_post.html',
                  {'form': form, 'submitted': submitted}
                  )

posts/templates/posts/_post.html
{% load blog_tags %}
<h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
<div class="post-meta">
    <span class="d-block"><a href="#">Autor: {{ post.author }}</a></span>
    <span class="date-read">{{ post.publish}}<span class="mx-1">&bullet;</span>{% if post.body|length > 750 %}
                10 min czytania
            {% else %}
                3 min czytania
            {% endif %} <span class="icon-star2"></span></span>
</div>
<p class="mb-3">{{ post.body|markdown|truncatewords_html:30 }}</p>
<p class="tags">{% for tag in post.tags.all  %}
    <a href="{% url  'posts:post_list_by_tag' tag.slug %}">#{{ tag.name }}</a>
    {% if not forloop.last %}{% endif %}
{% endfor %}
</p>

posts/templates/posts/actual.html
{% extends 'posts/post_base.html' %}
{% load blog_tags %}
{% block home %}
    {% the_newest_post %}
{% endblock %}

posts/templates/posts/add_image.html
{% extends 'posts/post_base.html' %}
{% block photo %}
<form id="post_form" method="post" action="" enctype="multipart/form-data">


    {% csrf_token %}
    {{ form.as_p }}
    {{ file_form.as_table }}
    <input type="submit" name="submit" value="Submit" />
</form>
{% endblock %}

posts/templates/posts/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="form-inline">
        <form method="POST"  class="form-inline">
            {% csrf_token %}
            <h2>Chcesz usunąć post: ,,{{ post.title }}'' ?</h2>
            <button type="submit" class="save btn btn-danger">Tak</button>
        </form>
        <a href="{% url 'home' %}"><button  class=" btn btn-info">Anuluj</button></a>
    </div>
{% endblock %}

posts/templates/posts/edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div>
        <h2>Edytuj post</h2>
        <form method="POST"  class="post-form">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="save btn btn-warning">Edycja</button>
        </form>
    </div>

{% endblock %}

{#action="{% url 'posts:edit_post' post.publish.year post.publish.month post.publish.day post.slug  %}"#}

posts/templates/posts/gallery.html
{% extends 'posts/post_base.html' %}
{% block gallery %}
    <div class="col-md-8">
        <h2>Galeria: </h2>
    {% for picture in image %}
        <h2><a href="{{ picture.get_absolute_url }}">{{ picture.title }}</a></h2>
        <img src="{{ picture.file.url }}" alt="" width="40%" >
    {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/gallery_detail.html
{% extends 'posts/post_base.html'%}
{% block image %}
    {% for image in images   %}
     <div class="col-md-8">
        <h1>{{ image.title }}</h1>
         <img src="{{ image.file.url }}" alt="">
       </div>
    {% endfor %}
{% endblock %}

posts/templates/posts/latest.html
{#{% extends 'base.html' %}#}
{#{% block latest %}#}
{% if latest_posts %}
{% for post in latest_posts %}
    <div class="trend-entry d-flex">
        <div class="number align-self-start">{{ post.id }}</div>
        <div class="trend-contents">
            <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            <div class="post-meta">
                <span class="d-block"><a href="#">{{ post.author }}</a></span>
                <span class="date-read">{{ post.publish }}<span class="mx-1">&bullet;</span>
            {% if post.body|length > 750 %}
                10 min czytania
            {% else %}
                3 min czytania
            {% endif %} <span class="icon-star2"></span></span>
            </div>
        </div>
    </div>
{% endfor %}
    {% else %}
     <div class="trend-entry d-flex">
        <div class="number align-self-start">0</div>
        <div class="trend-contents">
            <h2>Brak postów</h2>
        </div>
    </div>

{% endif %}

{#{% endblock %}#}

posts/templates/posts/newest.html
 <div class="col-md-8">
    {% for post in newest %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            <div class="post-meta">
                <span class="d-block"><a href="#">Autor: {{ post.author }}</a></span>
                <span class="date-read">{{ post.publish}}<span class="mx-1">&bullet;</span>{% if post.body|length > 750 %}
                10 min czytania
            {% else %}
                3 min czytania
            {% endif %}<span class="icon-star2"></span></span>
            </div>
            <p class="mb-3">{{ post.body|linebreaks }}</p>
            <p class="tags">{% for tag in post.tags.all  %}
                <a href="{% url  'posts:post_list_by_tag' tag.slug %}">#{{ tag.name }}</a>{% endfor %}
            </p>
        </div>
    {% endfor %}

posts/templates/posts/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
        {% endif %}
    <span class="current">
        Strona {{ page.number }} z {{ page.paginator.num_pages }}
    </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Następna</a>
        {% endif %}
    </span>
</div>

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
<h3>Are u sure to delete</h3>
    <div class="posts">
    {% include 'posts/_post.html' with post=object hide_delete=True %}
    </div>
    <form method="post">
    {% csrf_token %}
        <input type="submit" value="Confirm" class="btn btn-danger btn-large">
        <a href="{% url 'posts:post_detail' username=user.username pk=object.pk %}"
           class="btn btn-simple btn-large btn-default">Cancel</a>
    </form>
{% endblock %}

posts/templates/posts/projects_lists.html
{% extends 'posts/post_base.html' %}

{% block projects_content %}
    <div class="col-md-8">
    {% if tag %}
        <h2>Posty dla tagu #{{ tag.name }}</h2>
    {% endif %}
    {% for post in posts %}
        {% include 'posts/_post.html' %}
    {% endfor %}
    {% include 'posts/paginator.html' with page=posts %}
    </div>

{% endblock %}

posts/templates/posts/search.html
{% extends 'posts/post_base.html' %}
{% block search %}
    {% if results  %}
        <h1>Posty zawierające "{{ request.GET.q }}"</h1>
{#        <h3>Znaleziono {{ total_results }} wynik {{ total_results|pluralize:'i' }}</h3>#}
        {% for result in results %}
            {% with post=result %}
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title}}</a></h4>
                {{ post.body|truncatewords:30 }}
            {% endwith %}
        {% endfor %}
        {% else %}
        <h1>Brak wyników dla "{{ request.GET.q }}"</h1>
{% endif %}
{% endblock %}

posts/templates/posts/user_post.html
{% extends 'posts/post_base.html' %}
{% block prepost %}
    <div class="col-md-4">
    <h1>{{ post_user.username }}</h1>

    </div>

{% endblock %}
{% block post_content %}
    <div class="col-md-4">
    {% for foo in post_list %}
    {% include 'posts/_post.html' %}
    {% endfor %}

    </div>

{% endblock %}